
import javax.swing.JFrame;

/*
Joshua Pickenpaugh
February 22nd, 2017
MyVacationTime calculator
*/

/*

GUI

*/
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        this.setTitle("MyVacationTime");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtWeeks = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDays = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtMinutes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtUserInput = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Weeks:");

        txtWeeks.setEditable(false);
        txtWeeks.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(txtWeeks))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Days:");

        txtDays.setEditable(false);
        txtDays.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(txtDays))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hours:");

        txtHours.setEditable(false);
        txtHours.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(txtHours))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Minutes:");

        txtMinutes.setEditable(false);
        txtMinutes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(txtMinutes))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtUserInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnClear.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3, jPanel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Calculates the user-input decimal number to individual weeks, days, 
    //hours, and minutes of vacation time:
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        //Local variables:
        String strUserInput;
        String strFirstHalf;
        String strSecondHalf;
        double dblFirstHalf;  
        int intFirstHalf;
        
        //Gets user input:
        strUserInput = txtUserInput.getText();
         
        //Split the string:
        String[] strUserInputSplit = strUserInput.split("\\.");      
        
        //Assign each half a String variable:
        strFirstHalf = strUserInputSplit[0];
        strSecondHalf = strUserInputSplit[1];      
        
        //Convert to double:
        intFirstHalf = Integer.parseInt(strFirstHalf);
        
        //Calls function:
        GetWeeksDaysHours(intFirstHalf);   
        //Convert string hundredths of a minute to string actual minutes:
        ConvertToMinutes(strSecondHalf);   
    }//GEN-LAST:event_jButton1ActionPerformed

    //Clears the text boxes:
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtUserInput.setText("");
        txtWeeks.setText("");
        txtDays.setText("");
        txtHours.setText("");
        txtMinutes.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    //Gets weeks, days, and hours:
    public void GetWeeksDaysHours(int intFrstHalf)
    {
        //Local variables:
        int intWeeksCounter = 0;
        int intDaysCounter = 0;        
        double dblHours;        
        String strWeeks;
        String strDays;
        String strHours;     
        
        //Calcuates weeks, days, and hours:
        while (intFrstHalf >= 168)
        {
            intFrstHalf = intFrstHalf - 168;
            intWeeksCounter++;
        }
        while (intFrstHalf >= 24)
        {
            intFrstHalf = intFrstHalf - 24;
            intDaysCounter++;
        }
        dblHours = intFrstHalf;
        
        //Splits the decimal; we only need the whole number:
        strHours = Double.toString(dblHours);
        String[] strSplitHoursDecimal = strHours.split("\\.");
        strHours = strSplitHoursDecimal[0];   
        
        //Converts to strings:
        strWeeks = Integer.toString(intWeeksCounter);
        strDays = Integer.toString(intDaysCounter);
        
        //Displays to text boxes:
        txtWeeks.setText(strWeeks);
        txtDays.setText(strDays);
        txtHours.setText(strHours);
        
    }
 
    //Converts string hundreths of a minute to string actual minutes:
    public void ConvertToMinutes(String scndHalf)
    {              
        switch(scndHalf)
        {
            case "01":
                scndHalf = "01";
                break;
            case "02":
                scndHalf = "01";
                break;
            case "03":
                scndHalf = "02";
                break;
            case "04":
                scndHalf = "02";
                break;
            case "05":
                scndHalf = "03";
                break;
            case "06":
                scndHalf = "04";
                break;
            case "07":
                scndHalf = "04";
                break;
            case "08":
                scndHalf = "05";
                break;
            case "09":
                scndHalf = "05";
                break;
            case "10":
                scndHalf = "06";
                break;
            case "11":
                scndHalf = "07";
                break;
            case "12":
                scndHalf = "07";
                break;
            case "13":
                scndHalf = "08";
                break;
            case "14":
                scndHalf = "08";
                break;
            case "15":
                scndHalf = "09";
                break;
            case "16":
                scndHalf = "10";
                break;
            case "17":
                scndHalf = "10";
                break;
            case "18":
                scndHalf = "11";
                break;
            case "19":
                scndHalf = "11";
                break;
            case "20":
                scndHalf = "12";
                break;
            case "21":
                scndHalf = "13";
                break;
            case "22":
                scndHalf = "13";
                break;
            case "23":
                scndHalf = "14";
                break;
            case "24":
                scndHalf = "14";
                break;
            case "25":
                scndHalf = "15";
                break;
            case "26":
                scndHalf = "16";
                break;
            case "27":
                scndHalf = "16";
                break;
            case "28":
                scndHalf = "17";
                break;
            case "29":
                scndHalf = "17";
                break;
            case "30":
                scndHalf = "18";
                break;
            case "31":
                scndHalf = "19";
                break;
            case "32":
                scndHalf = "19";
                break;
            case "33":
                scndHalf = "20";
                break;
            case "34":
                scndHalf = "20";
                break;
            case "35":
                scndHalf = "21";
                break;
            case "36":
                scndHalf = "22";
                break;
            case "37":
                scndHalf = "22";
                break;
            case "38":
                scndHalf = "23";
                break;
            case "39":
                scndHalf = "23";
                break;
            case "40":
                scndHalf = "24";
                break;
            case "41":
                scndHalf = "25";
                break;
            case "42":
                scndHalf = "25";
                break;
            case "43":
                scndHalf = "26";
                break;
            case "44":
                scndHalf = "26";
                break;
            case "45":
                scndHalf = "27";
                break;
            case "46":
                scndHalf = "28";
                break;
            case "47":
                scndHalf = "28";
                break;
            case "48":
                scndHalf = "29";
                break;
            case "49":
                scndHalf = "29";
                break;
            case "50":
                scndHalf = "30";
                break;
            case "51":
                scndHalf = "31";
                break;
            case "52":
                scndHalf = "31";
                break;
            case "53":
                scndHalf = "32";
                break;
            case "54":
                scndHalf = "32";
                break;
            case "55":
                scndHalf = "33";
                break;
            case "56":
                scndHalf = "34";
                break;
            case "57":
                scndHalf = "34";
                break;
            case "58":
                scndHalf = "35";
                break;
            case "59":
                scndHalf = "35";
                break;
            case "60":
                scndHalf = "36";
                break;
            case "61":
                scndHalf = "37";
                break;
            case "62":
                scndHalf = "37";
                break;
            case "63":
                scndHalf = "38";
                break;
            case "64":
                scndHalf = "38";
                break;
            case "65":
                scndHalf = "39";
                break;
            case "66":
                scndHalf = "40";
                break;
            case "67":
                scndHalf = "40";
                break;
            case "68":
                scndHalf = "41";
                break;
            case "69":
                scndHalf = "41";
                break;
            case "70":
                scndHalf = "42";
                break;
            case "71":
                scndHalf = "43";
                break;
            case "72":
                scndHalf = "43";
                break;
            case "73":
                scndHalf = "44";
                break;
            case "74":
                scndHalf = "44";
                break;
            case "75":
                scndHalf = "45";
                break;
            case "76":
                scndHalf = "46";
                break;
            case "77":
                scndHalf = "46";
                break;
            case "78":
                scndHalf = "47";
                break;
            case "79":
                scndHalf = "47";
                break;
            case "80":
                scndHalf = "48";
                break;
            case "81":
                scndHalf = "49";
                break;
            case "82":
                scndHalf = "49";
                break;
            case "83":
                scndHalf = "50";
                break;
            case "84":
                scndHalf = "50";
                break;
            case "85":
                scndHalf = "51";
                break;
            case "86":
                scndHalf = "52";
                break;
            case "87":
                scndHalf = "52";
                break;
            case "88":
                scndHalf = "53";
                break;
            case "89":
                scndHalf = "53";
                break;
            case "90":
                scndHalf = "54";
                break;
            case "91":
                scndHalf = "55";
                break;
            case "92":
                scndHalf = "55";
                break;
            case "93":
                scndHalf = "56";
                break;
            case "94":
                scndHalf = "56";
                break;
            case "95":
                scndHalf = "57";
                break;
            case "96":
                scndHalf = "58";
                break;
            case "97":
                scndHalf = "58";
                break;
            case "98":
                scndHalf = "59";
                break;
            case "99":
                scndHalf = "59";
                break;
                
            default: 
                scndHalf = scndHalf;
                break;
        }
        //Displays the value in the text box:
        txtMinutes.setText(scndHalf);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtDays;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtMinutes;
    private javax.swing.JTextField txtUserInput;
    private javax.swing.JTextField txtWeeks;
    // End of variables declaration//GEN-END:variables
}
